<?php
/**
 * Its used for Client Language
 *
 * @since: 21/09/2021
 * @author: Sarwar Hasan
 * @version 1.0.0
 * @package VitePos_Lite\Libs
 */

namespace Minicart_Lite\Libs;

if ( ! class_exists( __NAMESPACE__ . '\App_Language' ) ) {
	/**
	 * Class VitePOS_API_Base
	 *
	 * @package VitePos_Lite\Libs
	 */
	class App_Language {
		/**
		 * The get Admin Languages is generated by appsbd
		 *
		 * @param mixed $kernel_object Its the object of kernel.
		 *
		 * @return mixed
		 */
		public static function get_admin_languages( &$kernel_object ) {
			$language                                                                                                                                         = array();
			$language['Settings']                                                                                                                             = $kernel_object->__( 'Settings' );
			$language['Open Customizer']                                                                                                                      = $kernel_object->__( 'Open Customizer' );
			$language['Mini Cart']                                                                                                                            = $kernel_object->__( 'Mini Cart' );
			$language['Sale Booster']                                                                                                                         = $kernel_object->__( 'Sale Booster' );
			$language['License Info']                                                                                                                         = $kernel_object->__( 'License Info' );
			$language['Recommended']                                                                                                                          = $kernel_object->__( 'Recommended' );
			$language['Video']                                                                                                                                = $kernel_object->__( 'Video' );
			$language['General Settings']                                                                                                                     = $kernel_object->__( 'General Settings' );
			$language['Type']                                                                                                                                 = $kernel_object->__( 'Type' );
			$language['Position']                                                                                                                             = $kernel_object->__( 'Position' );
			$language['Skin Type']                                                                                                                            = $kernel_object->__( 'Skin Type' );
			$language['Color']                                                                                                                                = $kernel_object->__( 'Color' );
			$language['Hide in Cart Page']                                                                                                                    = $kernel_object->__( 'Hide in Cart Page' );
			$language["if you enabled it, the mini cart doesn't show in cart page"]                                                                           = $kernel_object->__( "if you enabled it, the mini cart doesn't show in cart page" );
			$language['Hide in Checkout Page']                                                                                                                = $kernel_object->__( 'Hide in Checkout Page' );
			$language["if you enabled it, the mini cart doesn't show in checkout page"]                                                                       = $kernel_object->__( "if you enabled it, the mini cart doesn't show in checkout page" );
			$language['Hide On Pages']                                                                                                                        = $kernel_object->__( 'Hide On Pages' );
			$language['You can choose page where you want to hide the cart button']                                                                           = $kernel_object->__( 'You can choose page where you want to hide the cart button' );
			$language['Choose Pages']                                                                                                                         = $kernel_object->__( 'Choose Pages' );
			$language["Don't show when cart empty"]                                                                                                           = $kernel_object->__( "Don't show when cart empty" );
			$language["if you enabled it, the mini cart doesn't show when the cart is empty"]                                                                 = $kernel_object->__( "if you enabled it, the mini cart doesn't show when the cart is empty" );
			$language["Don't hide if there is undo button"]                                                                                                   = $kernel_object->__( "Don't hide if there is undo button" );
			$language['if you enabled it, the mini cart will display if there any product removed from cart']                                                 = $kernel_object->__( 'if you enabled it, the mini cart will display if there any product removed from cart' );
			$language['Cart content show on each item add']                                                                                                   = $kernel_object->__( 'Cart content show on each item add' );
			$language['if you enabled it, the mini cart item container will display on each cart add']                                                        = $kernel_object->__( 'if you enabled it, the mini cart item container will display on each cart add' );
			$language['Custom CSS']                                                                                                                           = $kernel_object->__( 'Custom CSS' );
			$language['Click the button to add custom css']                                                                                                   = $kernel_object->__( 'Click the button to add custom css' );
			$language['Add Custom CSS']                                                                                                                       = $kernel_object->__( 'Add Custom CSS' );
			$language['Add Menu Item']                                                                                                                        = $kernel_object->__( 'Add Menu Item' );
			$language['if you enabled it, it will show in menu item']                                                                                         = $kernel_object->__( 'if you enabled it, it will show in menu item' );
			$language['Choose Menu']                                                                                                                          = $kernel_object->__( 'Choose Menu' );
			$language['Show Icon Only']                                                                                                                       = $kernel_object->__( 'Show Icon Only' );
			$language['if you enabled it, then WooCommerce add message will not be shown']                                                                    = $kernel_object->__( 'if you enabled it, then WooCommerce add message will not be shown' );
			$language['Menu Title']                                                                                                                           = $kernel_object->__( 'Menu Title' );
			$language['It will show into header as title in cart']                                                                                            = $kernel_object->__( 'It will show into header as title in cart' );
			$language['Menu Icon']                                                                                                                            = $kernel_object->__( 'Menu Icon' );
			$language['Show Item Counter With Menu']                                                                                                          = $kernel_object->__( 'Show Item Counter With Menu' );
			$language['Menu Counter Type']                                                                                                                    = $kernel_object->__( 'Menu Counter Type' );
			$language['Total Item']                                                                                                                           = $kernel_object->__( 'Total Item' );
			$language['Total Quantity']                                                                                                                       = $kernel_object->__( 'Total Quantity' );
			$language['You can easily configure this using customizer, Click the button below to customize']                                                  = $kernel_object->__( 'You can easily configure this using customizer, Click the button below to customize' );
			$language['To get shortcode or other information, please click the button below']                                                                 = $kernel_object->__( 'To get shortcode or other information, please click the button below' );
			$language['View Info']                                                                                                                            = $kernel_object->__( 'View Info' );
			$language['Save']                                                                                                                                 = $kernel_object->__( 'Save' );
			$language['Button Settings']                                                                                                                      = $kernel_object->__( 'Button Settings' );
			$language['Size']                                                                                                                                 = $kernel_object->__( 'Size' );
			$language['Icon Size']                                                                                                                            = $kernel_object->__( 'Icon Size' );
			$language['Border Radius']                                                                                                                        = $kernel_object->__( 'Border Radius' );
			$language['Shadow Opacity']                                                                                                                       = $kernel_object->__( 'Shadow Opacity' );
			$language['Bottom Margin']                                                                                                                        = $kernel_object->__( 'Bottom Margin' );
			$language['Left Margin']                                                                                                                          = $kernel_object->__( 'Left Margin' );
			$language['Icon']                                                                                                                                 = $kernel_object->__( 'Icon' );
			$language['Display In Animation']                                                                                                                 = $kernel_object->__( 'Display In Animation' );
			$language['Display Out Animation']                                                                                                                = $kernel_object->__( 'Display Out Animation' );
			$language['Hide Circle']                                                                                                                          = $kernel_object->__( 'Hide Circle' );
			$language['if you enabled it, then circle counter of the top corner will be hide']                                                                = $kernel_object->__( 'if you enabled it, then circle counter of the top corner will be hide' );
			$language['Circle Counter Type']                                                                                                                  = $kernel_object->__( 'Circle Counter Type' );
			$language['Footer Content']                                                                                                                       = $kernel_object->__( 'Footer Content' );
			$language['TOTAL ITEMS']                                                                                                                          = $kernel_object->__( 'TOTAL ITEMS' );
			$language['TOTAL QUANTITIES']                                                                                                                     = $kernel_object->__( 'TOTAL QUANTITIES' );
			$language['TOTAL AMOUNT']                                                                                                                         = $kernel_object->__( 'TOTAL AMOUNT' );
			$language['Amount Type']                                                                                                                          = $kernel_object->__( 'Amount Type' );
			$language['Sub Total']                                                                                                                            = $kernel_object->__( 'Sub Total' );
			$language['Cart Total']                                                                                                                           = $kernel_object->__( 'Cart Total' );
			$language['Container Settings']                                                                                                                   = $kernel_object->__( 'Container Settings' );
			$language['Container Height']                                                                                                                     = $kernel_object->__( 'Container Height' );
			$language['Container Width']                                                                                                                      = $kernel_object->__( 'Container Width' );
			$language['Title Text']                                                                                                                           = $kernel_object->__( 'Title Text' );
			$language['Enable Cart Button']                                                                                                                   = $kernel_object->__( 'Enable Cart Button' );
			$language['if you enabled it, View full cart button will be displayed into cart footer']                                                          = $kernel_object->__( 'if you enabled it, View full cart button will be displayed into cart footer' );
			$language['Cart Button Text']                                                                                                                     = $kernel_object->__( 'Cart Button Text' );
			$language['It will show into the checkout button']                                                                                                = $kernel_object->__( 'It will show into the checkout button' );
			$language['Undo Remove Panel']                                                                                                                    = $kernel_object->__( 'Undo Remove Panel' );
			$language['if you enabled it, remove undo panel will be displayed into cart']                                                                     = $kernel_object->__( 'if you enabled it, remove undo panel will be displayed into cart' );
			$language['Show Discount and Cart Total']                                                                                                         = $kernel_object->__( 'Show Discount and Cart Total' );
			$language['if you enabled it, then discount and cart total will be displayed into cart']                                                          = $kernel_object->__( 'if you enabled it, then discount and cart total will be displayed into cart' );
			$language['Show All Fees']                                                                                                                        = $kernel_object->__( 'Show All Fees' );
			$language['if you enabled it, then shipping total, total fee, total tax will be displayed into cart']                                             = $kernel_object->__( 'if you enabled it, then shipping total, total fee, total tax will be displayed into cart' );
			$language['Show Coupon Input']                                                                                                                    = $kernel_object->__( 'Show Coupon Input' );
			$language['if you enabled it then coupon input box will be show in cart']                                                                         = $kernel_object->__( 'if you enabled it then coupon input box will be show in cart' );
			$language['Applied Coupon Panel']                                                                                                                 = $kernel_object->__( 'Applied Coupon Panel' );
			$language['if you enabled it then applied coupon panel will be displayed in cart']                                                                = $kernel_object->__( 'if you enabled it then applied coupon panel will be displayed in cart' );
			$language['Enable Checkout Button']                                                                                                               = $kernel_object->__( 'Enable Checkout Button' );
			$language['Checkout Button Text']                                                                                                                 = $kernel_object->__( 'Checkout Button Text' );
			$language['Cart Empty Text']                                                                                                                      = $kernel_object->__( 'Cart Empty Text' );
			$language['It will show into cart empty text']                                                                                                    = $kernel_object->__( 'It will show into cart empty text' );
			$language['Mini Cart Drawer Pro For WooCommerce']                                                                                                 = $kernel_object->__( 'Mini Cart Drawer Pro For WooCommerce' );
			$language['Discount Rules']                                                                                                                       = $kernel_object->__( 'Discount Rules' );
			$language['Reload']                                                                                                                               = $kernel_object->__( 'Reload' );
			$language['Add New Rule']                                                                                                                         = $kernel_object->__( 'Add New Rule' );
			$language['status']                                                                                                                               = $kernel_object->__( 'status' );
			$language['Status']                                                                                                                               = $kernel_object->__( 'Status' );
			$language['Cancel']                                                                                                                               = $kernel_object->__( 'Cancel' );
			$language['Close']                                                                                                                                = $kernel_object->__( 'Close' );
			$language['Edit Rule']                                                                                                                            = $kernel_object->__( 'Edit Rule' );
			$language['Loading Rule Details']                                                                                                                 = $kernel_object->__( 'Loading Rule Details' );
			$language['Click here to get video list']                                                                                                         = $kernel_object->__( 'Click here to get video list' );
			$language['Discount']                                                                                                                             = $kernel_object->__( 'Discount' );
			$language['Are you sure to delete this Rule?']                                                                                                    = $kernel_object->__( 'Are you sure to delete this Rule?' );
			$language['Right Margin']                                                                                                                         = $kernel_object->__( 'Right Margin' );
			$language['Message will be display when the target amount is greater then or equal $%{name}']                                                     = $kernel_object->__( 'Message will be display when the target amount is greater then or equal $%{name}' );
			$language['Fixed']                                                                                                                                = $kernel_object->__( 'Fixed' );
			$language['Active']                                                                                                                               = $kernel_object->__( 'Active' );
			$language['Loading Settings']                                                                                                                     = $kernel_object->__( 'Loading Settings' );
			$language['Inactive']                                                                                                                             = $kernel_object->__( 'Inactive' );
			$language['Yes']                                                                                                                                  = $kernel_object->__( 'Yes' );
			$language['No']                                                                                                                                   = $kernel_object->__( 'No' );
			$language['Offer Type']                                                                                                                           = $kernel_object->__( 'Offer Type' );
			$language['No rule added']                                                                                                                        = $kernel_object->__( 'No rule added' );
			$language['Discounts Rules']                                                                                                                      = $kernel_object->__( 'Discounts Rules' );
			$language['Right Bottom']                                                                                                                         = $kernel_object->__( 'Right Bottom' );
			$language['Right Middle']                                                                                                                         = $kernel_object->__( 'Right Middle' );
			$language['Right Top']                                                                                                                            = $kernel_object->__( 'Right Top' );
			$language['Drawer']                                                                                                                               = $kernel_object->__( 'Drawer' );
			$language['Left Bottom']                                                                                                                          = $kernel_object->__( 'Left Bottom' );
			$language['Left Middle']                                                                                                                          = $kernel_object->__( 'Left Middle' );
			$language['Floating']                                                                                                                             = $kernel_object->__( 'Floating' );
			$language['Left Top']                                                                                                                             = $kernel_object->__( 'Left Top' );
			$language['Shortcodes and other information']                                                                                                     = $kernel_object->__( 'Shortcodes and other information' );
			$language['Current Value']                                                                                                                        = $kernel_object->__( 'Current Value' );
			$language['If buyer spend $%{name} then he or she will get free shipping']                                                                        = $kernel_object->__( 'If buyer spend $%{name} then he or she will get free shipping' );
			$language['This module is available in pro version']                                                                                              = $kernel_object->__( 'This module is available in pro version' );
			$language['Unlock']                                                                                                                               = $kernel_object->__( 'Unlock' );
			$language['Details']                                                                                                                              = $kernel_object->__( 'Details' );
			$language['Subscribe']                                                                                                                            = $kernel_object->__( 'Subscribe' );
			$language["Don't show WC add message"]                                                                                                            = $kernel_object->__( "Don't show WC add message" );
			$language['Dynamic discount has been disabled in your site']                                                                                      = $kernel_object->__( 'Dynamic discount has been disabled in your site' );
			$language['Click here']                                                                                                                           = $kernel_object->__( 'Click here' );
			$language['to add new menu']                                                                                                                      = $kernel_object->__( 'to add new menu' );
			$language['Currently there is no menu has been created.']                                                                                         = $kernel_object->__( 'Currently there is no menu has been created.' );
			$language['Total Video(s)']                                                                                                                       = $kernel_object->__( 'Total Video(s)' );
			$language['Deactivate License']                                                                                                                   = $kernel_object->__( 'Deactivate License' );
			$language['Your License Key']                                                                                                                     = $kernel_object->__( 'Your License Key' );
			$language['License Expired on']                                                                                                                   = $kernel_object->__( 'License Expired on' );
			$language['Support Expired on']                                                                                                                   = $kernel_object->__( 'Support Expired on' );
			$language['License Type']                                                                                                                         = $kernel_object->__( 'License Type' );
			$language['License Status']                                                                                                                       = $kernel_object->__( 'License Status' );
			$language['Discount Amount']                                                                                                                      = $kernel_object->__( 'Discount Amount' );
			$language['Percentage %']                                                                                                                         = $kernel_object->__( 'Percentage %' );
			$language['Discount Type']                                                                                                                        = $kernel_object->__( 'Discount Type' );
			$language['Free Shipping']                                                                                                                        = $kernel_object->__( 'Free Shipping' );
			$language['When the message display on the screen, Message like, Spend more xx amount to get xx discount, It must be lower then target amount .'] = $kernel_object->__( 'When the message display on the screen, Message like, Spend more xx amount to get xx discount, It must be lower then target amount .' );
			$language['Target cart amount, if the cart amount greater then or equals to this amount then buyer will get offer.']                              = $kernel_object->__( 'Target cart amount, if the cart amount greater then or equals to this amount then buyer will get offer.' );
			$language['Display Amount']                                                                                                                       = $kernel_object->__( 'Display Amount' );
			$language['Target Amount']                                                                                                                        = $kernel_object->__( 'Target Amount' );
			$language['if you enabled it, discount info bar show in your site directly']                                                                      = $kernel_object->__( 'if you enabled it, discount info bar show in your site directly' );
			$language['Show Discount Bar In Site']                                                                                                            = $kernel_object->__( 'Show Discount Bar In Site' );
			$language['Discount Bar Settings']                                                                                                                = $kernel_object->__( 'Discount Bar Settings' );
			$language['Text Color']                                                                                                                           = $kernel_object->__( 'Text Color' );
			$language['Complete Color']                                                                                                                       = $kernel_object->__( 'Complete Color' );
			$language['Progressbar Background']                                                                                                               = $kernel_object->__( 'Progressbar Background' );
			$language['Choose Custom Color']                                                                                                                  = $kernel_object->__( 'Choose Custom Color' );
			$language['if you enabled it, discount info bar show in mini cart drawer']                                                                        = $kernel_object->__( 'if you enabled it, discount info bar show in mini cart drawer' );
			$language['Show in Mini Cart']                                                                                                                    = $kernel_object->__( 'Show in Mini Cart' );
			$language['Message in Mini Cart Settings']                                                                                                        = $kernel_object->__( 'Message in Mini Cart Settings' );
			$language['calculate_amount is for display calculated (target amount - current cart amount) amount value']                                        = $kernel_object->__( 'calculate_amount is for display calculated (target amount - current cart amount) amount value' );
			$language['Free Shipping Message']                                                                                                                = $kernel_object->__( 'Free Shipping Message' );
			$language['calculate_amount is for display calculated (target amount-current cart amount) amount value, offer_value is for discount value']       = $kernel_object->__( 'calculate_amount is for display calculated (target amount-current cart amount) amount value, offer_value is for discount value' );
			$language['Discount Message Amount']                                                                                                              = $kernel_object->__( 'Discount Message Amount' );
			$language['Discount Label']                                                                                                                       = $kernel_object->__( 'Discount Label' );
			$language['if you enabled it, then dynamic discount will be disabled when a buyer added coupon code in cart']                                     = $kernel_object->__( 'if you enabled it, then dynamic discount will be disabled when a buyer added coupon code in cart' );
			$language['if you enabled it, then dynamic discount rule will be applied in cart']                                                                = $kernel_object->__( 'if you enabled it, then dynamic discount rule will be applied in cart' );
			$language['Enable Dynamic Discount']                                                                                                              = $kernel_object->__( 'Enable Dynamic Discount' );
			$language['Dynamic Discounts Settings']                                                                                                           = $kernel_object->__( 'Dynamic Discounts Settings' );
			$language['Choose page for hide']                                                                                                                 = $kernel_object->__( 'Choose page for hide' );
						$language['Disable On Coupon']                                                                                                                 = $kernel_object->__( 'Disable On Coupon' );
			$language['Delete']                                                                                                                 = $kernel_object->__( 'Delete' );
			$language['base amount is required']                                                                                                                 = $kernel_object->__( 'base amount is required' );
			$language['view amount is required']                                                                                                                 = $kernel_object->__( 'view amount is required' );
			$language['Cart Shadow Opacity']      = $kernel_object->__( 'Cart Shadow Opacity' );
			$language['Cart Border Radius']      = $kernel_object->__( 'Cart Border Radius' );
			$language['Empty Cart Icon']      = $kernel_object->__( 'Empty Cart Icon' );
						$language['Customizer']      = $kernel_object->__( 'Customizer' );
			$language['Videos']      = $kernel_object->__( 'Videos' );
			$language['View Details']      = $kernel_object->__( 'View Details' );
			$language['Install']      = $kernel_object->__( 'Install' );
			$language['Version']      = $kernel_object->__( 'Version' );
			$language['Top']      = $kernel_object->__( 'Top' );
			$language['Bottom']      = $kernel_object->__( 'Bottom' );
			$language['Unlock it']      = $kernel_object->__( 'Unlock it' );
			$language['Click Here']      = $kernel_object->__( 'Click Here' );
			$language['Elite Licenser is a versatile WordPress plugin that handles product licensing, updates, license code generation, Envato license verification, full license control, and offers a comprehensive API for seamless integration with various applications.']      = $kernel_object->__( 'Elite Licenser is a versatile WordPress plugin that handles product licensing, updates, license code generation, Envato license verification, full license control, and offers a comprehensive API for seamless integration with various applications.' );
			$language['The Best Support Ticketing Software For Your Business! Best Support System, Best by name, Best by nature, Best by feature, it is a self-hosted customer support desk software. It handles support tickets, manages email tickets, collects any payment by PayPal.']      = $kernel_object->__( 'The Best Support Ticketing Software For Your Business! Best Support System, Best by name, Best by nature, Best by feature, it is a self-hosted customer support desk software. It handles support tickets, manages email tickets, collects any payment by PayPal.' );
			$language['Vitepos is a very fast and reliable point of sale (POS) plugin, Its fully responsive (mobile, tablet, laptop,desktop,large screen). It has been developed very latest technology also followed woocommerce development code standard.']      = $kernel_object->__( 'Vitepos is a very fast and reliable point of sale (POS) plugin, Its fully responsive (mobile, tablet, laptop,desktop,large screen). It has been developed very latest technology also followed woocommerce development code standard.' );
			$language['Loading Data...']      = $kernel_object->__( 'Loading Data...' );
			$language['is for display calculated (target amount-current cart amount) amount value']      = $kernel_object->__( 'is for display calculated (target amount-current cart amount) amount value' );
			$language['is for discount value']      = $kernel_object->__( 'is for discount value' );
			$language['is for display calculated (target amount - current cart amount) amount value']      = $kernel_object->__( 'is for display calculated (target amount - current cart amount) amount value' );
			$language['%{fld_name} is required']      = $kernel_object->__( '%{fld_name} is required' );
			$language['Please']      = $kernel_object->__( 'Please' );
			$language['to know the details about the product']      = $kernel_object->__( 'to know the details about the product' );
			$language['Loading Customizer...']      = $kernel_object->__( 'Loading Customizer...' );
			$language['Default']      = $kernel_object->__( 'Default' );
			$language['Pro Version']      = $kernel_object->__( 'Pro Version' );
			$language['To unlock these features, you need']      = $kernel_object->__( 'To unlock these features, you need' );
			$language['You will get these features in pro version']      = $kernel_object->__( 'You will get these features in pro version' );
			$language['Apply Coupon box can be displayed in mini cart']      = $kernel_object->__( 'Apply Coupon box can be displayed in mini cart' );
			$language['Applied Coupon box can be displayed in cart']      = $kernel_object->__( 'Applied Coupon box can be displayed in cart' );
			$language['You will get the wonderful Module called']      = $kernel_object->__( 'You will get the wonderful Module called' );
			$language['You will get premium support']      = $kernel_object->__( 'You will get premium support' );
			$language['Save Hide Pages']      = $kernel_object->__( 'Save Hide Pages' );
			$language['Save Custom CSS']      = $kernel_object->__( 'Save Custom CSS' );
			$language['You can attract your customers to purchase more items by offering many dynamic discounts, you can offer to your customer like, if you spend 20USD, then you will get 2USD discount.']      = $kernel_object->__( 'You can attract your customers to purchase more items by offering many dynamic discounts, you can offer to your customer like, if you spend 20USD, then you will get 2USD discount.' );

			$language['Valid']      = $kernel_object->__( 'Valid' );
			$language['Invalid']      = $kernel_object->__( 'Invalid' );
			$language['Email Address']      = $kernel_object->__( 'Email Address' );
			$language['License code']      = $kernel_object->__( 'License code' );
			$language['Activate']      = $kernel_object->__( 'Activate' );
			$language['Loading License Info...']      = $kernel_object->__( 'Loading License Info...' );
			$language['Enter your license key here, to activate the product, and get full feature updates and premium support.']      = $kernel_object->__( 'Enter your license key here, to activate the product, and get full feature updates and premium support.' );

			self::get_both_panel( $language, $kernel_object );

			return $language;
		}

		/**
		 * The get pos languages is generated by appsbd
		 *
		 * @param mixed $kernel_object Its the object of kernel.
		 *
		 * @return array
		 */
		public static function get_client_languages( &$kernel_object ) {
			$language                  = array();
			$language['have_a_coupon'] = $kernel_object->__( 'Have a coupon?' );
			$language['back']          = $kernel_object->__( 'Back' );
			$language['apply']         = $kernel_object->__( 'Apply' );
			$language['item']         = $kernel_object->__( 'item' );
			$language['items']         = $kernel_object->__( 'items' );
			$language['quantities']    = $kernel_object->__( 'quantities' );
			$language['quantity']    = $kernel_object->__( 'quantity' );
			$language['enter_code']    = $kernel_object->__( 'Enter coupon code' );
			$language['undo']    = $kernel_object->__( 'Undo' );
			$language['no']    = $kernel_object->__( 'No' );
			self::get_both_panel( $language, $kernel_object );

			return $language;
		}

		/**
		 * The get client extra is generated by appsbd
		 *
		 * @param any $language Its language array.
		 * @param any $kernel_object Its kernel Object.
		 */
		public static function get_both_panel( &$language, &$kernel_object ) {
		}
	}
}
